language: objective-c
osx_image: xcode11.2
script:
    - xcodebuild clean test -project "SwipingCarousel.xcodeproj" -scheme "Swiping Carousel" -destination "platform=iOS Simulator,name=iPhone 11,OS=13.2.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
